const ERROR_TOKEN_MISSING = "ERROR_TOKEN_MISSING";
const ERROR_INVALID_TOKEN = "ERROR_INVALID_TOKEN";
const ERROR_INTERNAL_SERVER_ERROR = "ERROR_INTERNAL_SERVER_ERROR";
const ERROR_FIELD_TASK_MISSING = "ERROR_TASK_MISSING";
const ERROR_FIELD_TASK_ID_MISSING = "ERROR_TASK_ID_MISSING";
const ERROR_NO_SUCH_PROJECT_FOUND_WITH_ID = "ERROR_NO_SUCH_PROJECT_FOUND_WITH_ID";
const ERROR_INVALID_FIELD = "ERROR_INVALID_FIELD";
const ERROR_FIELDS_MISSING = "ERROR_FIELDS_MISSING";
const ERROR_SUCH_SORTING_NOT_FOUND = "ERROR_SUCH_SORTING_NOT_FOUND";
const ERROR_EMAIL_ALREADY_IN_USE = "ERROR_EMAIL_ALREADY_EXISTS";
const ERROR_INVALID_EMAIL = "ERROR_INVALID_EMAIL"
const ERROR_INVALID_NAME = "ERROR_INVALID_NAME"
const ERROR_INVALID_PASSWORD = "ERROR_INVALID_PASSWORD"
const ERROR_INVALID_LASTNAME = "ERROR_INVALID_LASTNAME"
const ERROR_FIELDS_EMAIL_MALFORMED_OR_MISSING = "ERROR_FIELDS_EMAIL_MALFORMED_OR_MISSING";
const ERROR_FIELDS_PASSWORD_MALFORMED_OR_MISSING = "ERROR_FIELDS_PASSWORD_MALFORMED_OR_MISSING";
const ERROR_INVALID_EMAIL_OR_PASSWORD = "ERROR_INVALID_EMAIL_OR_PASSWORD";
const ERROR_NO_SUCH_USER_FOUND = "ERROR_NO_SUCH_USER_FOUND";
const ERROR_ACTIVE_INTERVALS_MISSING = "ERROR_ACTIVE_INTERVALS_MISSING";
const ERROR_INVALID_START_DATE = "ERROR_INVALID_START_DATE";
const ERROR_INVALID_STOP_DATE = "ERROR_INVALID_STOP_DATE";
const ERROR_THIS_PROJECT_ALREADY_ASSIGNED_ON_SAME_PLATE_NUMBER  = "ERROR_THIS_PROJECT_ALREADY_ASIGGNED_ON_SAME_PLATENUMBER"
const ERROR_NO_INTERVAL_FOUND_WITH_ID = "ERROR_NO_INTERVAL_FOUND_WITH_ID"
const SORTING = [
  "STARTED_NEWEST",
  "STARTED_OLDEST",
  "FINISHED_NEWEST",
  "FINISHED_OLDEST",
  "CREATED_NEWEST",
  "CREATED_OLDEST"
]

const STATUSES = [
  "ACTIVE",
  "FINISHED",
]

const ASSIGNMENT = [
  "ASSIGNED",
  "IDLE"
]

const ERRORS = {
  ERROR_TOKEN_MISSING,
  ERROR_INVALID_TOKEN,
  ERROR_INTERNAL_SERVER_ERROR,
  ERROR_FIELD_TASK_MISSING,
  ERROR_FIELD_TASK_ID_MISSING,
  ERROR_INVALID_FIELD,
  ERROR_NO_SUCH_PROJECT_FOUND_WITH_ID,
  ERROR_SUCH_SORTING_NOT_FOUND,
  ERROR_EMAIL_ALREADY_IN_USE,
  ERROR_FIELDS_EMAIL_MALFORMED_OR_MISSING,
  ERROR_FIELDS_PASSWORD_MALFORMED_OR_MISSING,
  ERROR_INVALID_EMAIL_OR_PASSWORD,
  ERROR_NO_SUCH_USER_FOUND,
  ERROR_INVALID_EMAIL,
  ERROR_INVALID_NAME,
  ERROR_INVALID_PASSWORD,
  ERROR_INVALID_LASTNAME,
  ERROR_FIELDS_MISSING,
  ERROR_ACTIVE_INTERVALS_MISSING,
  ERROR_INVALID_START_DATE,
  ERROR_INVALID_STOP_DATE,
  ERROR_THIS_PROJECT_ALREADY_ASSIGNED_ON_SAME_PLATE_NUMBER,
  ERROR_NO_INTERVAL_FOUND_WITH_ID
}
module.exports = {
  ERRORS,
  SORTING,
  STATUSES,
  ASSIGNMENT
}
